"""Markdown → self-contained HTML renderer.

Designed so non-dev users can be sent a single .html file (no images, no
external CSS, no JS deps) that opens cleanly in any browser.

Optional dependency: `markdown` (personalab[html]). Without it, we fall back
to a `<pre>` block of the raw markdown — still readable, just less pretty.
"""
from __future__ import annotations

import html as _html
import importlib.util
from pathlib import Path


_CSS = """
:root {
  --fg: #1a1a1a;
  --muted: #6b6b6b;
  --border: #e5e5e5;
  --bg: #fafafa;
  --code-bg: #f3f3f3;
  --quote-bg: #f9f9f9;
  --link: #2563eb;
  --p0: #dc2626;
  --p1: #ea580c;
  --p2: #d97706;
  --ok: #16a34a;
}
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    "Helvetica Neue", "PingFang SC", "Microsoft YaHei", sans-serif;
  font-size: 15px;
  line-height: 1.6;
  color: var(--fg);
  background: var(--bg);
  max-width: 880px;
  margin: 0 auto;
  padding: 32px 48px 96px;
}
h1 { font-size: 28px; margin: 0 0 8px; border-bottom: 2px solid var(--fg); padding-bottom: 8px; }
h2 { font-size: 22px; margin-top: 32px; border-bottom: 1px solid var(--border); padding-bottom: 4px; }
h3 { font-size: 18px; margin-top: 24px; }
h4 { font-size: 15px; margin-top: 18px; color: var(--muted); }
p, ul, ol { margin: 10px 0; }
ul, ol { padding-left: 28px; }
li { margin: 4px 0; }
strong { font-weight: 600; }
em { font-style: italic; }
a { color: var(--link); text-decoration: none; }
a:hover { text-decoration: underline; }
code {
  font-family: "JetBrains Mono", "SF Mono", Consolas, "Courier New", monospace;
  font-size: 13px;
  background: var(--code-bg);
  padding: 2px 6px;
  border-radius: 3px;
}
pre {
  background: var(--code-bg);
  padding: 12px 16px;
  border-radius: 4px;
  overflow-x: auto;
  font-size: 13px;
  line-height: 1.5;
}
pre code { background: transparent; padding: 0; }
blockquote {
  margin: 12px 0;
  padding: 8px 16px;
  border-left: 4px solid var(--border);
  background: var(--quote-bg);
  color: var(--muted);
  font-style: italic;
}
table {
  border-collapse: collapse;
  width: 100%;
  margin: 16px 0;
  font-size: 14px;
}
th, td {
  border: 1px solid var(--border);
  padding: 8px 12px;
  text-align: left;
  vertical-align: top;
}
th { background: var(--code-bg); font-weight: 600; }
tr:nth-child(even) td { background: #fcfcfc; }
hr { border: none; border-top: 1px solid var(--border); margin: 32px 0; }
.banner {
  border: 1px solid var(--border);
  background: white;
  padding: 12px 18px;
  border-radius: 6px;
  font-size: 13px;
  color: var(--muted);
  margin-bottom: 16px;
}
"""


def _have_markdown() -> bool:
    return importlib.util.find_spec("markdown") is not None


def markdown_to_html(md_text: str, title: str = "personalab report") -> str:
    if _have_markdown():
        import markdown as _md
        body = _md.markdown(
            md_text,
            extensions=["tables", "fenced_code", "sane_lists", "nl2br"],
            output_format="html5",
        )
    else:
        body = ("<div class='banner'>⚠️ <code>markdown</code> package not "
                "installed — showing raw source. <code>pip install "
                "personalab[html]</code> for rendered output.</div>"
                f"<pre>{_html.escape(md_text)}</pre>")
    return (
        "<!DOCTYPE html>\n"
        "<html lang=\"zh\">\n"
        "<head>\n"
        "<meta charset=\"utf-8\">\n"
        f"<title>{_html.escape(title)}</title>\n"
        f"<style>{_CSS}</style>\n"
        "</head>\n"
        "<body>\n"
        "<div class='banner'>📄 Generated by "
        "<a href=\"https://github.com/personalab/personalab\">personalab</a> "
        "— share this file with anyone, no dependencies needed.</div>\n"
        f"{body}\n"
        "</body>\n"
        "</html>\n"
    )


def render_md_to_html(md_path: Path | str, out_path: Path | str | None = None,
                       title: str | None = None) -> Path:
    md_path = Path(md_path)
    text = md_path.read_text("utf-8")
    html = markdown_to_html(text, title=title or md_path.stem)
    out = Path(out_path) if out_path else md_path.with_suffix(".html")
    out.write_text(html, encoding="utf-8")
    return out


def render_dir_md_to_html(directory: Path | str) -> list[Path]:
    """Render every *.md in dir to a sibling *.html. Returns list of paths."""
    d = Path(directory)
    out: list[Path] = []
    for md in d.glob("*.md"):
        out.append(render_md_to_html(md))
    return out
